export default {
  selectRoot: {
    width: '100%',
    margin: '32px 0 8px',
    fontFamily: 'CircularStd',
    fontSize: '16px',
    letterSpacing: '0.25px',
    lineHeight: '19px',
    textAlign: 'left',
  },
  menuItemRoot: {
    fontFamily: 'CircularStd',
    letterSpacing: '0.25px',
    lineHeight: '19px',
    textAlign: 'left',
  },
  close: {
    backgroundColor: '#FFF',
    color: '#48D7BE',
    fontFamily: 'CircularStd',
    fontSize: '14px',
    fontWeight: 500,
    letterSpacing: '0.22px',
    lineHeight: '17px',
    textAlign: 'left',
    textTransform: 'capitalize',
    '&:hover': {
      backgroundColor: '#FFF',
    },
  },
  send: {
    backgroundColor: '#48D7BE',
    color: '#fff',
    fontFamily: 'CircularStd',
    fontSize: '14px',
    fontWeight: 500,
    letterSpacing: '0.22px',
    lineHeight: '17px',
    textAlign: 'left',
    textTransform: 'capitalize',
    marginLeft: '8px',
    '&:hover': {
      backgroundColor: '#48D7BE',
    },
  },
};
