export default {
  fab: {
    position: 'absolute',
    bottom: 66,
    right: 32,
    backgroundColor: '#48D7BE',
    color: '#fff',
    fontFamily: 'CircularStd',
    fontSize: '14px',
    fontWeight: 500,
    letterSpacing: '0.22px',
    lineHeight: '17px',
    textAlign: 'left',
    textTransform: 'capitalize',
    width: '111px',
    '&:hover': {
      backgroundColor: '#48D7BE',
    },
  },
  chip: {
    backgroundColor: '#FBF9FF',
    color: '#48D7BE',
    fontFamily: 'CircularStd',
    fontSize: '14px',
    fontWeight: 500,
    letterSpacing: '0.22px',
    lineHeight: '17px',
    textAlign: 'left',
    textTransform: 'capitalize',
    marginRight: '8px',
    '&:hover': {
      backgroundColor: '#FBF9FF',
    },
  },
  chipSelected: {
    backgroundImage: 'linear-gradient(135.91deg, #48D7BE 0%, #58F4D9 100%)',
    color: '#FFFFFF',
    fontFamily: 'CircularStd',
    fontSize: '14px',
    fontWeight: 500,
    letterSpacing: '0.22px',
    lineHeight: '17px',
    textAlign: 'left',
    textTransform: 'capitalize',
    marginRight: '8px',
    borderRadius: '12px',
    boxShadow: '0 2px 3px 0 rgba(0, 0, 0, 0.16)',
    '&:hover': {
      backgroundImage: 'linear-gradient(135.91deg, #48D7BE 0%, #58F4D9 100%)',
      borderRadius: '12px',
      boxShadow: '0 2px 3px 0 rgba(0, 0, 0, 0.16)',
      color: '#FFFFFF',
    },
  },
};
